const pulls = {
  'badge': 22,
  'matrix-project': 61,
  'structs': 53,
  'junit': 122,
  'script-security': 264,
  'plugin-usage': 11,
  'parallel-test-executor': 90,
  'timestamper': 37,
  'login-theme-plugin': 4,
  'blueocean': 2033,
  'xml-job-to-job-dsl': 3,
  'fortify-on-demand-uploader-plugin': 79,
  'mabl-integration': 23,
  'xcode': 107,
  'build-name-setter-plugin': 51,
  'display-url-api': 28,
  'mac': 1,
  'credentials-plugin': 128,
  'versioncolumn-plugin': 4,
};
module.exports = pulls;
